import unittest

class TestClass14(unittest.TestCase):
    def testCase01(self):
        raise Exception